0 0 dataAuditErrors
1 0 non45Errors
2 0 offGridErrors
235 0 offGridShapeErrors: off grid polygon on layer Bondpad
238 0 offGridShapeErrors: off grid polygon on layer CapMetal
241 0 offGridShapeErrors: off grid polygon on layer Cont
244 0 offGridShapeErrors: off grid polygon on layer ESDdummy
247 0 offGridShapeErrors: off grid polygon on layer IND2dummy
250 0 offGridShapeErrors: off grid polygon on layer IND3dummy
253 0 offGridShapeErrors: off grid polygon on layer INDdummy
256 0 offGridShapeErrors: off grid polygon on layer M1Resdum
259 0 offGridShapeErrors: off grid polygon on layer M2Resdum
262 0 offGridShapeErrors: off grid polygon on layer M3Resdum
265 0 offGridShapeErrors: off grid polygon on layer M4Resdum
268 0 offGridShapeErrors: off grid polygon on layer M5Resdum
271 0 offGridShapeErrors: off grid polygon on layer M6Resdum
274 0 offGridShapeErrors: off grid polygon on layer M7Resdum
277 0 offGridShapeErrors: off grid polygon on layer M8Resdum
280 0 offGridShapeErrors: off grid polygon on layer M9Resdum
283 0 offGridShapeErrors: off grid polygon on layer Metal1_d
286 0 offGridShapeErrors: off grid polygon on layer Metal1_f
289 0 offGridShapeErrors: off grid polygon on layer Metal1_n
292 0 offGridShapeErrors: off grid polygon on layer Metal1_p
295 0 offGridShapeErrors: off grid polygon on layer Metal1_slot
298 0 offGridShapeErrors: off grid polygon on layer Metal2_d
301 0 offGridShapeErrors: off grid polygon on layer Metal2_f
304 0 offGridShapeErrors: off grid polygon on layer Metal2_n
307 0 offGridShapeErrors: off grid polygon on layer Metal2_p
310 0 offGridShapeErrors: off grid polygon on layer Metal2_slot
313 0 offGridShapeErrors: off grid polygon on layer Metal3_d
316 0 offGridShapeErrors: off grid polygon on layer Metal3_f
319 0 offGridShapeErrors: off grid polygon on layer Metal3_n
322 0 offGridShapeErrors: off grid polygon on layer Metal3_p
325 0 offGridShapeErrors: off grid polygon on layer Metal3_slot
328 0 offGridShapeErrors: off grid polygon on layer Metal4_d
331 0 offGridShapeErrors: off grid polygon on layer Metal4_f
334 0 offGridShapeErrors: off grid polygon on layer Metal4_n
337 0 offGridShapeErrors: off grid polygon on layer Metal4_p
340 0 offGridShapeErrors: off grid polygon on layer Metal4_slot
343 0 offGridShapeErrors: off grid polygon on layer Metal5_d
346 0 offGridShapeErrors: off grid polygon on layer Metal5_f
349 0 offGridShapeErrors: off grid polygon on layer Metal5_n
352 0 offGridShapeErrors: off grid polygon on layer Metal5_p
355 0 offGridShapeErrors: off grid polygon on layer Metal5_slot
358 0 offGridShapeErrors: off grid polygon on layer Metal6_d
361 0 offGridShapeErrors: off grid polygon on layer Metal6_f
364 0 offGridShapeErrors: off grid polygon on layer Metal6_n
367 0 offGridShapeErrors: off grid polygon on layer Metal6_p
370 0 offGridShapeErrors: off grid polygon on layer Metal6_slot
373 0 offGridShapeErrors: off grid polygon on layer Metal7_d
376 0 offGridShapeErrors: off grid polygon on layer Metal7_f
379 0 offGridShapeErrors: off grid polygon on layer Metal7_n
382 0 offGridShapeErrors: off grid polygon on layer Metal7_p
385 0 offGridShapeErrors: off grid polygon on layer Metal7_slot
388 0 offGridShapeErrors: off grid polygon on layer Metal8_d
391 0 offGridShapeErrors: off grid polygon on layer Metal8_f
394 0 offGridShapeErrors: off grid polygon on layer Metal8_n
397 0 offGridShapeErrors: off grid polygon on layer Metal8_p
400 0 offGridShapeErrors: off grid polygon on layer Metal8_slot
403 0 offGridShapeErrors: off grid polygon on layer Metal9_d
406 0 offGridShapeErrors: off grid polygon on layer Metal9_f
409 0 offGridShapeErrors: off grid polygon on layer Metal9_n
412 0 offGridShapeErrors: off grid polygon on layer Metal9_p
415 0 offGridShapeErrors: off grid polygon on layer Metal9_slot
418 0 offGridShapeErrors: off grid polygon on layer NPNdummy
421 0 offGridShapeErrors: off grid polygon on layer Nburied
424 0 offGridShapeErrors: off grid polygon on layer Nhvt
427 0 offGridShapeErrors: off grid polygon on layer Nimp
430 0 offGridShapeErrors: off grid polygon on layer Nwell
433 0 offGridShapeErrors: off grid polygon on layer Nzvt
436 0 offGridShapeErrors: off grid polygon on layer Oxide
439 0 offGridShapeErrors: off grid polygon on layer Oxide_thk
442 0 offGridShapeErrors: off grid polygon on layer PNPdummy
445 0 offGridShapeErrors: off grid polygon on layer Phvt
448 0 offGridShapeErrors: off grid polygon on layer Pimp
451 0 offGridShapeErrors: off grid polygon on layer Poly
454 0 offGridShapeErrors: off grid polygon on layer Psub
457 0 offGridShapeErrors: off grid polygon on layer ResWdum
460 0 offGridShapeErrors: off grid polygon on layer Resdum
463 0 offGridShapeErrors: off grid polygon on layer SiProt
466 0 offGridShapeErrors: off grid polygon on layer Via1
469 0 offGridShapeErrors: off grid polygon on layer Via2
472 0 offGridShapeErrors: off grid polygon on layer Via3
475 0 offGridShapeErrors: off grid polygon on layer Via4
478 0 offGridShapeErrors: off grid polygon on layer Via5
481 0 offGridShapeErrors: off grid polygon on layer Via6
484 0 offGridShapeErrors: off grid polygon on layer Via7
487 0 offGridShapeErrors: off grid polygon on layer Via8
488 0 non45 degree polygon on layer Bondpad
489 0 non45 degree polygon on layer CapMetal
491 0 non45 degree polygon on layer Cont
493 0 non45 degree polygon on layer ESDdummy
495 0 non45 degree polygon on layer IND2dummy
497 0 non45 degree polygon on layer IND3dummy
498 0 non45 degree polygon on layer INDdummy
500 0 non45 degree polygon on layer M1Resdum
502 0 non45 degree polygon on layer M2Resdum
504 0 non45 degree polygon on layer M3Resdum
506 0 non45 degree polygon on layer M4Resdum
508 0 non45 degree polygon on layer M5Resdum
510 0 non45 degree polygon on layer M6Resdum
512 0 non45 degree polygon on layer M7Resdum
514 0 non45 degree polygon on layer M8Resdum
516 0 non45 degree polygon on layer M9Resdum
517 0 non45 degree polygon on layer Metal1_d
519 0 non45 degree polygon on layer Metal1_f
521 0 non45 degree polygon on layer Metal1_n
522 0 non45 degree polygon on layer Metal1_p
524 0 non45 degree polygon on layer Metal1_slot
525 0 non45 degree polygon on layer Metal2_d
527 0 non45 degree polygon on layer Metal2_f
529 0 non45 degree polygon on layer Metal2_n
530 0 non45 degree polygon on layer Metal2_p
532 0 non45 degree polygon on layer Metal2_slot
533 0 non45 degree polygon on layer Metal3_d
535 0 non45 degree polygon on layer Metal3_f
537 0 non45 degree polygon on layer Metal3_n
538 0 non45 degree polygon on layer Metal3_p
540 0 non45 degree polygon on layer Metal3_slot
541 0 non45 degree polygon on layer Metal4_d
543 0 non45 degree polygon on layer Metal4_f
545 0 non45 degree polygon on layer Metal4_n
546 0 non45 degree polygon on layer Metal4_p
548 0 non45 degree polygon on layer Metal4_slot
549 0 non45 degree polygon on layer Metal5_d
551 0 non45 degree polygon on layer Metal5_f
553 0 non45 degree polygon on layer Metal5_n
554 0 non45 degree polygon on layer Metal5_p
556 0 non45 degree polygon on layer Metal5_slot
557 0 non45 degree polygon on layer Metal6_d
559 0 non45 degree polygon on layer Metal6_f
561 0 non45 degree polygon on layer Metal6_n
562 0 non45 degree polygon on layer Metal6_p
564 0 non45 degree polygon on layer Metal6_slot
565 0 non45 degree polygon on layer Metal7_d
567 0 non45 degree polygon on layer Metal7_f
569 0 non45 degree polygon on layer Metal7_n
570 0 non45 degree polygon on layer Metal7_p
572 0 non45 degree polygon on layer Metal7_slot
573 0 non45 degree polygon on layer Metal8_d
575 0 non45 degree polygon on layer Metal8_f
577 0 non45 degree polygon on layer Metal8_n
578 0 non45 degree polygon on layer Metal8_p
580 0 non45 degree polygon on layer Metal8_slot
581 0 non45 degree polygon on layer Metal9_d
583 0 non45 degree polygon on layer Metal9_f
585 0 non45 degree polygon on layer Metal9_n
586 0 non45 degree polygon on layer Metal9_p
588 0 non45 degree polygon on layer Metal9_slot
590 0 non45 degree polygon on layer NPNdummy
591 0 non45 degree polygon on layer Nburied
593 0 non45 degree polygon on layer Nhvt
594 0 non45 degree polygon on layer Nimp
595 0 non45 degree polygon on layer Nwell
597 0 non45 degree polygon on layer Nzvt
599 0 non45 degree polygon on layer Oxide
601 0 non45 degree polygon on layer Oxide_thk
603 0 non45 degree polygon on layer PNPdummy
605 0 non45 degree polygon on layer Phvt
606 0 non45 degree polygon on layer Pimp
607 0 non45 degree polygon on layer Poly
608 0 non45 degree polygon on layer Psub
610 0 non45 degree polygon on layer ResWdum
612 0 non45 degree polygon on layer Resdum
614 0 non45 degree polygon on layer SiProt
616 0 non45 degree polygon on layer Via1
618 0 non45 degree polygon on layer Via2
620 0 non45 degree polygon on layer Via3
622 0 non45 degree polygon on layer Via4
624 0 non45 degree polygon on layer Via5
626 0 non45 degree polygon on layer Via6
628 0 non45 degree polygon on layer Via7
630 0 non45 degree polygon on layer Via8
631 0 acute angle on layer Bondpad
632 0 acute angle on layer CapMetal
633 0 acute angle on layer ESDdummy
634 0 acute angle on layer IND2dummy
635 0 acute angle on layer IND3dummy
636 0 acute angle on layer INDdummy
637 0 acute angle on layer M1Resdum
638 0 acute angle on layer M2Resdum
639 0 acute angle on layer M3Resdum
640 0 acute angle on layer M4Resdum
641 0 acute angle on layer M5Resdum
642 0 acute angle on layer M6Resdum
643 0 acute angle on layer M7Resdum
644 0 acute angle on layer M8Resdum
645 0 acute angle on layer M9Resdum
646 0 acute angle on layer Metal1_d
647 0 acute angle on layer Metal1_f
648 0 acute angle on layer Metal1_n
649 0 acute angle on layer Metal1_p
650 0 acute angle on layer Metal1_slot
651 0 acute angle on layer Metal2_d
652 0 acute angle on layer Metal2_f
653 0 acute angle on layer Metal2_n
654 0 acute angle on layer Metal2_p
655 0 acute angle on layer Metal2_slot
656 0 acute angle on layer Metal3_d
657 0 acute angle on layer Metal3_f
658 0 acute angle on layer Metal3_n
659 0 acute angle on layer Metal3_p
660 0 acute angle on layer Metal3_slot
661 0 acute angle on layer Metal4_d
662 0 acute angle on layer Metal4_f
663 0 acute angle on layer Metal4_n
664 0 acute angle on layer Metal4_p
665 0 acute angle on layer Metal4_slot
666 0 acute angle on layer Metal5_d
667 0 acute angle on layer Metal5_f
668 0 acute angle on layer Metal5_n
669 0 acute angle on layer Metal5_p
670 0 acute angle on layer Metal5_slot
671 0 acute angle on layer Metal6_d
672 0 acute angle on layer Metal6_f
673 0 acute angle on layer Metal6_n
674 0 acute angle on layer Metal6_p
675 0 acute angle on layer Metal6_slot
676 0 acute angle on layer Metal7_d
677 0 acute angle on layer Metal7_f
678 0 acute angle on layer Metal7_n
679 0 acute angle on layer Metal7_p
680 0 acute angle on layer Metal7_slot
681 0 acute angle on layer Metal8_d
682 0 acute angle on layer Metal8_f
683 0 acute angle on layer Metal8_n
684 0 acute angle on layer Metal8_p
685 0 acute angle on layer Metal8_slot
686 0 acute angle on layer Metal9_d
687 0 acute angle on layer Metal9_f
688 0 acute angle on layer Metal9_n
689 0 acute angle on layer Metal9_p
690 0 acute angle on layer Metal9_slot
691 0 acute angle on layer NPNdummy
692 0 acute angle on layer Nhvt
693 0 acute angle on layer PNPdummy
694 0 acute angle on layer Phvt
695 0 acute angle on layer Psub
696 0 acute angle on layer ResWdum
697 0 acute angle on layer Resdum
723 0 NZVT.X.4: Only one Oxide region may be in an Nzvt region
836 0 BONDPAD.L.1: Bondpad length must be >= 68.0 um
840 0 NBL.X.1: Nburied must have an Nwell isolation ring
844 0 NHVT.X.1: Nhvt to Oxide enclosure must be == 0.0 on all sides
848 0 PHVT.X.1: Phvt to Oxide enclosure must be == 0.0 on all sides
852 0 BONDPAD.O.1: Bondpads must contain Metal 1
858 0 BONDPAD.O.1: Bondpads must contain Metal 2
867 0 BONDPAD.O.1: Bondpads must contain Metal 3
873 0 BONDPAD.O.1: Bondpads must contain Metal 4
879 0 BONDPAD.O.1: Bondpads must contain Metal 5
885 0 BONDPAD.O.1: Bondpads must contain Metal 6
891 0 BONDPAD.O.1: Bondpads must contain Metal 7
897 0 BONDPAD.O.1: Bondpads must contain Metal 8
904 0 BONDPAD.O.1: Bondpads must contain Metal 9
945 0 NZVT.O.1: Nzvt to Oxide enclosure must be == 0.3
1196 0 BONDPAD.O.2: Bondpad Metal1/Metal2 intersection must contain Via 1
1201 0 BONDPAD.O.2: Bondpad Metal2/Metal3 intersection must contain Via 2
1206 0 BONDPAD.O.2: Bondpad Metal3/Metal4 intersection must contain Via 3
1211 0 BONDPAD.O.2: Bondpad Metal4/Metal5 intersection must contain Via 4
1216 0 BONDPAD.O.2: Bondpad Metal5/Metal6 intersection must contain Via 5
1221 0 BONDPAD.O.2: Bondpad Metal6/Metal7 intersection must contain Via 6
1226 0 BONDPAD.O.2: Bondpad Metal7/Metal8 intersection must contain Via 7
1231 0 BONDPAD.O.2: Bondpad Metal8/Metal9 intersection must contain Via 8
1627 0 POLY.SE.3: Poly width, between two contacts spaced > 25.0um, must be >= 0.14um
1639 0 BONDPAD.SP.5: Bondpad Metal1 slot to Bondpad Metal1 slot spacing must be == 1.50
1643 0 BONDPAD.W.4: Bondpad Metal1 slot width must be == 1.00
1654 0 BONDPAD.R.1: Minimum Bondpad Via1 inside Metal1 to Metal2 crossing must be >= 16.0
1659 0 BONDPAD.SP.5: Bondpad Metal2 slot to Bondpad Metal2 slot spacing must be == 1.50
1663 0 BONDPAD.W.4: Bondpad Metal2 slot width must be == 1.00
1674 0 BONDPAD.R.1: Minimum Bondpad Via2 inside Metal2 to Metal3 crossing must be >= 16.0
1679 0 BONDPAD.SP.5: Bondpad Metal3 slot to Bondpad Metal3 slot spacing must be == 1.50
1683 0 BONDPAD.W.4: Bondpad Metal3 slot width must be == 1.00
1694 0 BONDPAD.R.1: Minimum Bondpad Via3 inside Metal3 to Metal4 crossing must be >= 16.0
1699 0 BONDPAD.SP.5: Bondpad Metal4 slot to Bondpad Metal4 slot spacing must be == 1.50
1703 0 BONDPAD.W.4: Bondpad Metal4 slot width must be == 1.00
1714 0 BONDPAD.R.1: Minimum Bondpad Via4 inside Metal4 to Metal5 crossing must be >= 16.0
1719 0 BONDPAD.SP.5: Bondpad Metal5 slot to Bondpad Metal5 slot spacing must be == 1.50
1723 0 BONDPAD.W.4: Bondpad Metal5 slot width must be == 1.00
1734 0 BONDPAD.R.1: Minimum Bondpad Via5 inside Metal5 to Metal6 crossing must be >= 16.0
1739 0 BONDPAD.SP.5: Bondpad Metal6 slot to Bondpad Metal6 slot spacing must be == 1.50
1743 0 BONDPAD.W.4: Bondpad Metal6 slot width must be == 1.00
1754 0 BONDPAD.R.1: Minimum Bondpad Via6 inside Metal6 to Metal7 crossing must be >= 16.0
1759 0 BONDPAD.SP.5: Bondpad Metal7 slot to Bondpad Metal7 slot spacing must be == 1.50
1763 0 BONDPAD.W.4: Bondpad Metal7 slot width must be == 1.00
1774 0 BONDPAD.R.2: Minimum Bondpad Via7 inside Metal7 to Metal8 crossing must be >= 4.0
1779 0 BONDPAD.SP.5: Bondpad Metal8 slot to Bondpad Metal8 slot spacing must be == 1.50
1783 0 BONDPAD.W.4: Bondpad Metal8 slot width must be == 1.00
1788 0 BONDPAD.R.2: Minimum Bondpad Via8 inside Metal8 to Metal9 crossing must be >= 4.0
2469 0 OXIDE.L.1_OXIDE.L.2: Maximum Oxide length between two contacts (when the Oxide width is <= 0.18um) must be <= 22.0um and Maximum Oxide length between one contact and the end of the Oxide line (when the Oxide width is <= 0.18um) must be <= 11.0um
2497 0 BONDPAD.W.5: Bondpad Metal1 outside Metal1 ring width must be == 5.00
2525 0 BONDPAD.W.5: Bondpad Metal2 outside Metal2 ring width must be == 5.00
2553 0 BONDPAD.W.5: Bondpad Metal3 outside Metal3 ring width must be == 5.00
2581 0 BONDPAD.W.5: Bondpad Metal4 outside Metal4 ring width must be == 5.00
2609 0 BONDPAD.W.5: Bondpad Metal5 outside Metal5 ring width must be == 5.00
2637 0 BONDPAD.W.5: Bondpad Metal6 outside Metal6 ring width must be == 5.00
2665 0 BONDPAD.W.5: Bondpad Metal7 outside Metal7 ring width must be == 5.00
2693 0 BONDPAD.W.5: Bondpad Metal8 outside Metal8 ring width must be == 5.00
2713 0 VIA1.X.2: Metal1 must connect to Metal2 with >= 4 Via1 spaced < 0.30 um or >= 9 Via1 spaced < 0.60 um
2732 0 VIA2.X.2: Metal2 must connect to Metal3 with >= 4 Via2 spaced < 0.30 um or >= 9 Via2 spaced < 0.60 um
2752 0 VIA3.X.2: Metal3 must connect to Metal4 with >= 4 Via3 spaced < 0.30 um or >= 9 Via3 spaced < 0.60 um
2772 0 VIA4.X.2: Metal4 must connect to Metal5 with >= 4 Via4 spaced < 0.30 um or >= 9 Via4 spaced < 0.60 um
2792 0 VIA5.X.2: Metal5 must connect to Metal6 with >= 4 Via5 spaced < 0.30 um or >= 9 Via5 spaced < 0.60 um
2812 0 VIA6.X.2: Metal6 must connect to Metal7 with >= 4 Via6 spaced < 0.30 um or >= 9 Via6 spaced < 0.60 um
2832 0 VIA1.X.1: Metal1 must connect to Metal2 with >= 2 Via1 spaced < 0.30 um or >= 4 Via1 spaced < 0.60 um
2852 0 VIA2.X.1: Metal2 must connect to Metal3 with >= 2 Via2 spaced < 0.30 um or >= 4 Via2 spaced < 0.60 um
2872 0 VIA3.X.1: Metal3 must connect to Metal4 with >= 2 Via3 spaced < 0.30 um or >= 4 Via3 spaced < 0.60 um
2892 0 VIA4.X.1: Metal4 must connect to Metal5 with >= 2 Via4 spaced < 0.30 um or >= 4 Via4 spaced < 0.60 um
2912 0 VIA5.X.1: Metal5 must connect to Metal6 with >= 2 Via5 spaced < 0.30 um or >= 4 Via5 spaced < 0.60 um
2932 0 VIA6.X.1: Metal6 must connect to Metal7 with >= 2 Via6 spaced < 0.30 um or >= 4 Via6 spaced < 0.60 um
2938 0 BONDPAD.B.1: Bondpad Metal1 must have bevelled corners
2944 0 BONDPAD.B.1: Bondpad Metal2 must have bevelled corners
2950 0 BONDPAD.B.1: Bondpad Metal3 must have bevelled corners
2956 0 BONDPAD.B.1: Bondpad Metal4 must have bevelled corners
2962 0 BONDPAD.B.1: Bondpad Metal5 must have bevelled corners
2968 0 BONDPAD.B.1: Bondpad Metal6 must have bevelled corners
2974 0 BONDPAD.B.1: Bondpad Metal7 must have bevelled corners
2980 0 BONDPAD.B.1: Bondpad Metal8 must have bevelled corners
2986 0 BONDPAD.B.1: Bondpad Metal9 must have bevelled corners
2988 0 ptap_StampErrorFloat
2989 0 ptap_StampErrorMult
2990 0 ptap_StampErrorConnect
2995 0 psubstrate_StampErrorFloat
2996 0 psubstrate_StampErrorMult
2997 0 psubstrate_StampErrorConnect
3002 0 ntap_StampErrorFloat
3003 0 ntap_StampErrorMult
3004 0 ntap_StampErrorConnect
3009 0 nwell_conn_StampErrorFloat
3010 0 nwell_conn_StampErrorMult
3011 0 nwell_conn_StampErrorConnect
3016 0 nb_tap_StampErrorFloat
3017 0 nb_tap_StampErrorMult
3018 0 nb_tap_StampErrorConnect
3023 0 Nburied_StampErrorFloat
3024 0 Nburied_StampErrorMult
3025 0 Nburied_StampErrorConnect
3063 0 NBL.W.1: Nburied width must be >= 3.2 um
3065 0 NBL.E.1: Nburied to Nwell enclosure must be >= 0.4 um
3067 0 NBL.SP.1: Nburied to Nburied spacing must be >= 5.0 um
3070 0 NBL.SE.2: Nburied to Oxide spacing must be >= 2.2 um
3071 0 NBL.SE.2: Nburied to Oxide spacing must be >= 2.2 um
3072 0 NBL.SE.1: Nburied to non-related Nwell spacing must be >= 4.4 um
3077 0 NBL.SE.3: Nwell ring (on Nburied) to P+ Oxide spacing must be >= 0.5 um
3079 0 NBL.SE.3: Nwell ring (on Nburied) to P+ Oxide spacing must be >= 0.5 um
3083 0 NBL.SE.4: Nwell ring (on Nburied) to N+ Oxide spacing must be >= 0.4 um
3085 0 NBL.SE.4: Nwell ring (on Nburied) to N+ Oxide spacing must be >= 0.4 um
3087 0 NW.SP.1: Nwell to Nwell spacing (same potential) must be >= 0.6 um
3089 0 NW.SP.1: Nwell to Nwell spacing (same potential) must be >= 0.6 um
3092 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3093 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3095 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3096 0 NW.W.1: Nwell width must be >= 0.6 um
3100 0 NW.SP.2: Nwell to Nwell spacing (diferent potential) must be >= 1.2 um
3101 0 NW.SE.1: Nwell to Oxide spacing must be >= 0.3 um
3104 0 NW.SE.2: Nwell to P+ Oxide spacing must be >= 0.3 um
3105 0 NW.SE.2: Nwell to P+ Oxide spacing must be >= 0.3 um
3110 0 NW.SE.3: Nwell to N+ 2.5V Oxide spacing must be >= 0.5 um
3111 0 NW.SE.3: Nwell to N+ 2.5V Oxide spacing must be >= 0.5 um
3116 0 NW.SE.4: Nwell to P+ 2.5V Oxide spacing must be >= 0.5 um
3117 0 NW.SE.4: Nwell to P+ 2.5V Oxide spacing must be >= 0.5 um
3122 0 NW.E.1: Nwell to N+ Oxide enclosure must be >= 0.12 um
3123 0 NW.E.2: Nwell to P+ Oxide enclosure must be >= 0.12 um
3125 0 NW.E.2: Nwell to P+ Oxide enclosure must be >= 0.12 um
3126 0 NW.E.3: Nwell to N+ 2.5V Oxide enclosure must be >= 0.7 um
3128 0 NW.E.3: Nwell to N+ 2.5V Oxide enclosure must be >= 0.7 um
3129 0 NW.E.4: Nwell to P+ 2.5V Oxide enclosure must be >= 0.7 um
3131 0 NW.E.4: Nwell to P+ 2.5V Oxide enclosure must be >= 0.7 um
3132 0 NWR.SE.1: Nwell (in resistor) to SiProt spacing must be >= 0.32 um
3134 0 NWR.E.1: Oxide to Nwell (in resistor) enclosure must be >= 1.2 um
3136 0 NWR.E.1: Oxide to Nwell (in resistor) enclosure must be >= 1.2 um
3138 0 NWR.E.2: Nwell (in resistor) to Cont enclosure must be >= 0.32 um
3140 0 NWR.E.2: Nwell (in resistor) to Cont enclosure must be >= 0.32 um
3141 0 NWR.O.1: SiProt to Nimp overlap must be >= 0.45 um
3142 0 NWR.X.1: Thick Oxide is NOT allowed over Nwell resistor
3143 0 OXIDE.W.1: Oxide width must be >= 0.1 um
3148 0 OXIDE.W.2.1.1: 1.2V N-channel gate width must be >= 0.12 um
3152 0 OXIDE.W.2.1.2: 2.5V N-channel gate width must be >= 0.15 um
3157 0 OXIDE.W.2.2.1: 1.2V P-channel gate width must be >= 0.12 um
3161 0 OXIDE.W.2.2.2: 2.5V P-channel gate width must be >= 0.15 um
3163 0 OXIDE.W.3: Oxide (45 degree) width must be >= 0.13 um
3165 0 OXIDE.SP.1: N+ Oxide to N+ Oxide spacing must be >= 0.15 um
3167 0 OXIDE.SP.2: P+ Oxide to P+ Oxide spacing must be >= 0.15 um
3172 0 OXIDE.SP.3: P+ Oxide to P+ Oxide spacing must be >= 0.15 um
3173 0 OXIDE.SE.1: Oxide to Oxide_thk spacing must be >= 0.28 um
3174 0 OXIDE.SP.4: Oxide bent 45 degree to Oxide spacing must be >= 0.18 um
3175 0 OXIDE.A.1: Oxide area must be >= 0.06 um
3179 0 OXIDE.EA.1: Oxide enclosed area must be >= 0.10 um
3183 0 OXIDE.X.1: Oxide must be covered by Nimp or Pimp or Nzvt
3186 0 OXIDER.SE.2: Oxide resistor to Nimp spacing must be >= 0.3 um
3187 0 OXIDER.SE.2: Oxide resistor to Nimp spacing must be >= 0.3 um
3190 0 OXIDER.SE.2: Oxide resistor to Pimp spacing must be >= 0.3 um
3191 0 OXIDER.SE.2: Oxide resistor to Pimp spacing must be >= 0.3 um
3193 0 OXIDER.E.1: SiProt to Oxide resistor enclosure must be >= 0.25 um
3195 0 OXIDER.X.1: Oxide resistors must have N+ or P+ Implant
3196 0 OXIDETHK.W.1: Oxide_thk width must be >= 0.7 um
3198 0 OXIDETHK.SP.1: Oxide_thk to Oxide_thk spacing must be >= 0.35 um
3200 0 OXIDETHK.SP.2: Oxide_thk (bent 45 degree) to Oxide_thk spacing must be >= 0.75 um
3202 0 OXIDETHK.SE.1: 2.5V N+ Oxide to 2.5V N+ Oxide spacing must be >= 0.20 um
3204 0 OXIDETHK.SE.2: 2.5V P+ Oxide to 2.5V P+ Oxide spacing must be >= 0.20 um
3209 0 OXIDETHK.SE.3: 2.5V N+ Oxide to 2.5V P+ Oxide spacing must be >= 0.25 um
3211 0 OXIDETHK.E.1: Oxide_thk to Oxide enclosure must be >= 0.30 um
3218 0 OXIDETHK.SE.5: Oxide_thk to Poly gate spacing must be >= 0.34 um
3219 0 OXIDETHK.SE.5: Oxide_thk to Poly gate spacing must be >= 0.34 um
3221 0 OXIDETHK.E.2: Oxide_thk to Poly gate enclosure must be >= 0.36 um
3222 0 NHVT.X.2: Nhvt is NOT allowed on Nwell
3223 0 NHVT.X.3: Nhvt is NOT allowed on P+ Oxide
3224 0 NHVT.X.4: Nhvt is NOT allowed on Nzvt
3225 0 PHVT.X.2: Phvt is NOT allowed outside Nwell
3226 0 PHVT.X.3: Phvt is NOT allowed on N+ Oxide
3227 0 PHVT.X.4: Phvt is NOT allowed on Nzvt
3228 0 NZVT.W.1: Nzvt width must be >= 0.7 um
3230 0 NZVT.SP.1: Nzvt to Nzvt spacing must be >= 0.6 um
3233 0 NZVT.SE.1: Nzvt to Oxide spacing must be >= 0.28 um
3234 0 NZVT.SE.1: Nzvt to Oxide spacing must be >= 0.28 um
3235 0 NZVT.SE.2: Nzvt to Nwell spacing must be >= 1.2 um
3236 0 NZVT.SE.2: Nzvt to Nwell spacing must be >= 1.2 um
3239 0 NZVT.E.1: Poly to Oxide enclosure must be >= 0.2 um
3242 0 NZVT.L.1: Native Device Poly gate length must be >= 0.9 um
3246 0 NZVT.W.2: Native Device Poly gate width must be >= 0.65 um
3248 0 NZVT.X.3: P+ Oxide is NOT allowed in Nzvt
3251 0 POLY.W.1: 1.2V N+ Poly gate length must be >= 0.1 um
3254 0 POLY.W.2: 1.2V P+ Poly gate length must be >= 0.1 um
3258 0 POLY.W.3: 2.5V N+ Poly gate length must be >= 0.28 um
3263 0 POLY.W.4: 2.5V P+ Poly gate length must be >= 0.28 um
3266 0 POLY.W.5: Poly interconnect width must be >= 0.1 um
3270 0 POLY.SP.1: Poly resistor to Poly resistor spacing must be >= 0.6 um
3272 0 POLY.SP.2: Poly gate to Poly gate spacing must be >= 0.12 um
3274 0 POLY.SP.3: Poly interconnect to Poly interconnect spacing must be >= 0.12 um
3276 0 POLY.E.1: Poly to N+ Oxide enclosure must be >= 0.18 um
3278 0 POLY.E.2: Poly to P+ Oxide enclosure must be >= 0.18 um
3279 0 POLY.SE.1_POLY.SE.2: Poly to Oxide spacing must be >= 0.1 um
3281 0 POLY.E.3: Oxide to Poly enclosure must be >= 0.2 um
3283 0 POLY.W.6: Bent Poly width must be >= 0.18 um
3285 0 POLY.SP.4: Bent Poly to bent Poly spacing must be >= 0.22 um
3286 0 POLY.X.1: Poly gate cannot have bends
3287 0 POLY.X.2: Poly resistor cannot have bends
3288 0 POLY.A.1: Poly area must be >= 0.1 um
3290 0 POLYR.E.1: SiProt to Poly resistor enclosure must be >= 0.28 um
3292 0 POLYR.E.2: Nimp to Poly used in resistor enclosure must be >= 0.15 um
3294 0 POLYR.E.2: Nimp to Poly used in resistor enclosure must be >= 0.15 um
3296 0 POLYR.E.3: Pimp to Poly used in resistor enclosure must be >= 0.15 um
3298 0 POLYR.E.3: Pimp to Poly used in resistor enclosure must be >= 0.15 um
3300 0 POLYR.SE.2: Poly resistor to Nimp spacing must be >= 0.3 um
3301 0 POLYR.SE.2: Poly resistor to Nimp spacing must be >= 0.3 um
3302 0 POLYR.SE.2: Poly resistor to Nzvt spacing must be >= 0.3 um
3303 0 POLYR.SE.2: Poly resistor to Nzvt spacing must be >= 0.3 um
3305 0 POLYR.SE.2: Poly resistor to Pimp spacing must be >= 0.3 um
3306 0 POLYR.SE.2: Poly resistor to Pimp spacing must be >= 0.3 um
3307 0 POLYR.X.1: Poly resistors must have N+ or P+ Implant
3308 0 NIMP.W.1: Nimp width must be >= 0.24 um
3310 0 NIMP.SP.1: Nimp to Nimp spacing must be >= 0.24 um
3313 0 NIMP.E.1: Nimp to Oxide enclosure must be >= 0.14 um
3314 0 NIMP.O.1: Nimp to Oxide overlap must be >= 0.16 um
3322 0 NIMP.SE.1: Nimp to P+ Oxide spacing must be >= 0.16 um
3323 0 NIMP.SE.1: Nimp to P+ Oxide spacing must be >= 0.16 um
3326 0 NIMP.E.2: Nimp to Oxide (Nwell tie) enclosure must be >= 0.02 um
3330 0 NIMP.E.3: Nimp to Poly gate enclosure must be >= 0.18 um
3336 0 NIMP.E.4: Nimp to gate end enclosure must be >= 0.18 um
3338 0 NIMP.E.4: Nimp to gate end enclosure must be >= 0.18 um
3347 0 NIMP.SE.2: Nimp to P+ Oxide spacing must be >= 0.02 um
3348 0 NIMP.SE.2: Nimp to P+ Oxide spacing must be >= 0.02 um
3349 0 NIMP.A.1: Nimp area must be >= 0.15 um
3353 0 NIMP.EA.1: Area in Nimp ring must be >= 0.16 um
3356 0 NIMP.SE.3: Nimp to P+ gate spacing must be >= 0.18 um
3357 0 NIMP.SE.3: Nimp to P+ gate spacing must be >= 0.18 um
3358 0 NIMP.X.1: Nimp is NOT allowed over Pimp
3359 0 PIMP.W.1: Pimp width must be >= 0.24 um
3361 0 PIMP.SP.1: Pimp to Pimp spacing must be >= 0.24 um
3363 0 PIMP.E.1: Pimp to Oxide enclosure must be >= 0.14 um
3364 0 PIMP.O.1: Pimp to Oxide overlap must be >= 0.16 um
3372 0 PIMP.SE.1: Pimp to N+ Oxide spacing must be >= 0.16 um
3373 0 PIMP.SE.1: Pimp to N+ Oxide spacing must be >= 0.16 um
3375 0 PIMP.E.2: Pimp to Oxide (substrate tie) enclosure must be >= 0.02 um
3379 0 PIMP.E.3: Pimp to Poly gate enclosure must be >= 0.18 um
3382 0 PIMP.E.4: Pimp to gate end enclosure must be >= 0.18 um
3384 0 PIMP.E.4: Pimp to gate end enclosure must be >= 0.18 um
3393 0 PIMP.SE.2: Pimp to N+ Oxide spacing must be >= 0.02 um
3394 0 PIMP.SE.2: Pimp to N+ Oxide spacing must be >= 0.02 um
3395 0 PIMP.A.1: Pimp area must be >= 0.15 um
3399 0 PIMP.EA.1: Area in Pimp ring must be >= 0.16 um
3402 0 PIMP.SE.3: Pimp to N+ gate spacing must be >= 0.18 um
3403 0 PIMP.SE.3: Pimp to N+ gate spacing must be >= 0.18 um
3405 0 CONT.W.1: Cont shapes must be 0.12x0.12 rectangles
3407 0 CONT.SP.1: Cont to Cont spacing must be >= 0.14 um
3410 0 CONT.SP.2: Cont to Cont (in array) spacing must be >= 0.16 um
3413 0 CONT.SE.1: Cont to gate spacing must be >= 0.10 um
3414 0 CONT.SE.1: Cont to gate spacing must be >= 0.10 um
3420 0 CONT.SE.2: Cont to 2.5V gate spacing must be >= 0.12 um
3421 0 CONT.SE.2: Cont to 2.5V gate spacing must be >= 0.12 um
3423 0 CONT.SE.3: Poly Cont to Oxide spacing must be >= 0.12 um
3424 0 CONT.SE.3: Poly Cont to Oxide spacing must be >= 0.12 um
3429 0 CONT.SE.4: Poly Cont to Oxide spacing must be >= 0.14 um
3430 0 CONT.SE.4: Poly Cont to Oxide spacing must be >= 0.14 um
3432 0 CONT.E.1: Oxide to Cont enclosure must be >= 0.06 um
3434 0 CONT.E.1: Oxide to Cont enclosure must be >= 0.06 um
3436 0 CONT.E.2: Poly to Cont enclosure must be >= 0.04 um
3438 0 CONT.E.2: Poly to Cont enclosure must be >= 0.04 um
3441 0 CONT.E.3: Poly to Cont enclosure on at least two opposite sides must be >= 0.06 um
3443 0 CONT.E.4: Nimp to Cont enclosure must be >= 0.06 um
3445 0 CONT.E.4: Nimp to Cont enclosure must be >= 0.06 um
3447 0 CONT.E.4: Pimp to Cont enclosure must be >= 0.06 um
3449 0 CONT.E.4: Pimp to Cont enclosure must be >= 0.06 um
3451 0 CONT.X.1: Cont on gate is NOT allowed
3454 0 CONT.X.2: Nimp edge is NOT allowed on Oxide Cont
3457 0 CONT.X.2: Pimp edge is NOT allowed on Oxide Cont
3458 0 CONT.X.3: Cont must be covered by Oxide or Poly
3459 0 SIPROT.W.1: SiProt width must be >= 0.44 um
3461 0 SIPROT.SP.1: SiProt to SiProt spacing must be >= 0.44 um
3464 0 SIPROT.SE.1: SiProt to Cont spacing must be >= 0.24 um
3465 0 SIPROT.SE.1: SiProt to Cont spacing must be >= 0.24 um
3466 0 SIPROT.SE.2: SiProt to Oxide spacing must be >= 0.24 um
3470 0 SIPROT.SE.3: SiProt to Poly gate spacing must be >= 0.44 um
3471 0 SIPROT.SE.3: SiProt to Poly gate spacing must be >= 0.44 um
3473 0 SIPROT.E.2: Oxide to SiProt enclosure must be >= 0.24 um
3477 0 SIPROT.E.1: SiProt to Oxide enclosure must be >= 0.25 um
3479 0 SIPROT.E.3: SiProt to Poly enclosure must be >= 0.28 um
3480 0 SIPROT.A.1: SiProt area must be >= 1.2 um
3481 0 SIPROT.SE.4: SiProt to Poly (on field) spacing must be >= 0.35 um
3485 0 SIPROT.EA.1: Area in SiProt ring must be >= 1.2 um
3486 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
3488 0 METAL2.E.1: Metal2 to Via1 enclosure must be >= 0.005 um
3492 0 METAL2.E.2: Metal2 to Via1 enclosure on opposite sides must be >= 0.06 um
3493 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
3495 0 METAL3.E.1: Metal3 to Via2 enclosure must be >= 0.005 um
3499 0 METAL3.E.2: Metal3 to Via2 enclosure on opposite sides must be >= 0.06 um
3500 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
3502 0 METAL4.E.1: Metal4 to Via3 enclosure must be >= 0.005 um
3506 0 METAL4.E.2: Metal4 to Via3 enclosure on opposite sides must be >= 0.06 um
3507 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
3509 0 METAL5.E.1: Metal5 to Via4 enclosure must be >= 0.005 um
3513 0 METAL5.E.2: Metal5 to Via4 enclosure on opposite sides must be >= 0.06 um
3514 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
3516 0 METAL6.E.1: Metal6 to Via5 enclosure must be >= 0.005 um
3520 0 METAL6.E.2: Metal6 to Via5 enclosure on opposite sides must be >= 0.06 um
3521 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
3523 0 METAL7.E.1: Metal7 to Via6 enclosure must be >= 0.005 um
3527 0 METAL7.E.2: Metal7 to Via6 enclosure on opposite sides must be >= 0.06 um
3528 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.05 um
3530 0 METAL8.E.1: Metal8 to Via7 enclosure must be >= 0.05 um
3534 0 METAL8.E.2: Metal8 to Via7 enclosure on opposite sides must be >= 0.1 um
3535 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.05 um
3537 0 METAL9.E.1: Metal9 to Via8 enclosure must be >= 0.05 um
3541 0 METAL9.E.2: Metal9 to Via8 enclosure on opposite sides must be >= 0.1 um
3542 0 METAL1.E.1: Metal1 to Cont enclosure must be >= 0.00 um
3546 0 METAL1.E.2: Metal1 to Cont enclosure on opposite sides must be >= 0.06 um
3547 0 METAL1.W.1: Metal1 width must be >= 0.12 um
3548 0 METAL2.W.1: Metal2 width must be >= 0.14 um
3549 0 METAL3.W.1: Metal3 width must be >= 0.14 um
3550 0 METAL4.W.1: Metal4 width must be >= 0.14 um
3551 0 METAL5.W.1: Metal5 width must be >= 0.14 um
3552 0 METAL6.W.1: Metal6 width must be >= 0.14 um
3553 0 METAL7.W.1: Metal7 width must be >= 0.14 um
3554 0 METAL8.W.1: Metal8 width must be >= 0.44 um
3555 0 METAL9.W.1: Metal9 width must be >= 0.44 um
3559 0 METAL1.W.2: Metal1 width must be <= 12.0 um
3563 0 METAL2.W.2: Metal2 width must be <= 12.0 um
3567 0 METAL3.W.2: Metal3 width must be <= 12.0 um
3571 0 METAL4.W.2: Metal4 width must be <= 12.0 um
3575 0 METAL5.W.2: Metal5 width must be <= 12.0 um
3579 0 METAL6.W.2: Metal6 width must be <= 12.0 um
3582 0 METAL7.W.2: Metal7 width must be <= 12.0 um
3584 0 METAL8.W.2: Metal8 width must be <= 12.0 um
3586 0 METAL9.W.2: Metal9 width must be <= 12.0 um
3588 0 METAL1.SP.1.1: Metal1 to Metal1 spacing must be >= 0.12 um
3590 0 METAL2.SP.1.1: Metal2 to Metal2 spacing must be >= 0.14 um
3592 0 METAL3.SP.1.1: Metal3 to Metal3 spacing must be >= 0.14 um
3594 0 METAL4.SP.1.1: Metal4 to Metal4 spacing must be >= 0.14 um
3596 0 METAL5.SP.1.1: Metal5 to Metal5 spacing must be >= 0.14 um
3598 0 METAL6.SP.1.1: Metal6 to Metal6 spacing must be >= 0.14 um
3600 0 METAL7.SP.1.1: Metal7 to Metal7 spacing must be >= 0.14 um
3602 0 METAL8.SP.1.1: Metal8 to Metal8 spacing must be >= 0.40 um
3604 0 METAL9.SP.1.1: Metal9 to Metal9 spacing must be >= 0.40 um
3611 0 METAL1.SP.1.2: Metal1 to Metal1 spacing must be >= 0.18 um
3618 0 METAL2.SP.1.2: Metal2 to Metal2 spacing must be >= 0.20 um
3625 0 METAL3.SP.1.2: Metal3 to Metal3 spacing must be >= 0.20 um
3632 0 METAL4.SP.1.2: Metal4 to Metal4 spacing must be >= 0.20 um
3639 0 METAL5.SP.1.2: Metal5 to Metal5 spacing must be >= 0.20 um
3646 0 METAL6.SP.1.2: Metal6 to Metal6 spacing must be >= 0.20 um
3653 0 METAL7.SP.1.2: Metal7 to Metal7 spacing must be >= 0.20 um
3660 0 METAL1.SP.1.3: Metal1 to Metal1 spacing must be >= 0.50 um
3667 0 METAL2.SP.1.3: Metal2 to Metal2 spacing must be >= 0.50 um
3674 0 METAL3.SP.1.3: Metal3 to Metal3 spacing must be >= 0.50 um
3681 0 METAL4.SP.1.3: Metal4 to Metal4 spacing must be >= 0.50 um
3688 0 METAL5.SP.1.3: Metal5 to Metal5 spacing must be >= 0.50 um
3695 0 METAL6.SP.1.3: Metal6 to Metal6 spacing must be >= 0.50 um
3702 0 METAL7.SP.1.3: Metal7 to Metal7 spacing must be >= 0.50 um
3709 0 METAL8.SP.1.2: Metal8 to Metal8 spacing must be >= 0.50 um
3716 0 METAL9.SP.1.2: Metal9 to Metal9 spacing must be >= 0.50 um
3723 0 METAL1.SP.1.4: Metal1 to Metal1 spacing must be >= 0.90 um
3730 0 METAL2.SP.1.4: Metal2 to Metal2 spacing must be >= 0.90 um
3737 0 METAL3.SP.1.4: Metal3 to Metal3 spacing must be >= 0.90 um
3744 0 METAL4.SP.1.4: Metal4 to Metal4 spacing must be >= 0.90 um
3751 0 METAL5.SP.1.4: Metal5 to Metal5 spacing must be >= 0.90 um
3758 0 METAL6.SP.1.4: Metal6 to Metal6 spacing must be >= 0.90 um
3765 0 METAL7.SP.1.4: Metal7 to Metal7 spacing must be >= 0.90 um
3772 0 METAL8.SP.1.3: Metal8 to Metal8 spacing must be >= 0.90 um
3779 0 METAL9.SP.1.3: Metal9 to Metal9 spacing must be >= 0.90 um
3786 0 METAL1.SP.1.5: Metal1 to Metal1 spacing must be >= 1.50 um
3793 0 METAL2.SP.1.5: Metal2 to Metal2 spacing must be >= 1.50 um
3800 0 METAL3.SP.1.5: Metal3 to Metal3 spacing must be >= 1.50 um
3807 0 METAL4.SP.1.5: Metal4 to Metal4 spacing must be >= 1.50 um
3814 0 METAL5.SP.1.5: Metal5 to Metal5 spacing must be >= 1.50 um
3821 0 METAL6.SP.1.5: Metal6 to Metal6 spacing must be >= 1.50 um
3828 0 METAL7.SP.1.5: Metal7 to Metal7 spacing must be >= 1.50 um
3835 0 METAL8.SP.1.4: Metal8 to Metal8 spacing must be >= 1.50 um
3842 0 METAL9.SP.1.4: Metal9 to Metal9 spacing must be >= 1.50 um
3847 0 METAL1.SP.1.6: Metal1 to Metal1 spacing must be >= 2.50 um
3852 0 METAL2.SP.1.6: Metal2 to Metal2 spacing must be >= 2.50 um
3857 0 METAL3.SP.1.6: Metal3 to Metal3 spacing must be >= 2.50 um
3862 0 METAL4.SP.1.6: Metal4 to Metal4 spacing must be >= 2.50 um
3867 0 METAL5.SP.1.6: Metal5 to Metal5 spacing must be >= 2.50 um
3872 0 METAL6.SP.1.6: Metal6 to Metal6 spacing must be >= 2.50 um
3877 0 METAL7.SP.1.6: Metal7 to Metal7 spacing must be >= 2.50 um
3882 0 METAL8.SP.1.5: Metal8 to Metal8 spacing must be >= 2.50 um
3887 0 METAL9.SP.1.5: Metal9 to Metal9 spacing must be >= 2.50 um
3889 0 METAL1.L.1: Metal1 non-90 degree segments must be >= 0.18 um
3891 0 METAL2.L.1: Metal2 non-90 degree segments must be >= 0.20 um
3893 0 METAL3.L.1: Metal3 non-90 degree segments must be >= 0.20 um
3895 0 METAL4.L.1: Metal4 non-90 degree segments must be >= 0.20 um
3897 0 METAL5.L.1: Metal5 non-90 degree segments must be >= 0.20 um
3899 0 METAL6.L.1: Metal6 non-90 degree segments must be >= 0.20 um
3901 0 METAL7.L.1: Metal7 non-90 degree segments must be >= 0.20 um
3902 0 METAL1.SP.2: Metal1 to bent Metal1 spacing must be >= 0.16 um
3903 0 METAL1.W.3: Bent Metal1 (45 degree angle) width must be >= 0.14
3904 0 METAL2.SP.2: Metal2 to bent Metal2 spacing must be >= 0.18 um
3905 0 METAL2.W.3: Bent Metal2 (45 degree angle) width must be >= 0.16
3906 0 METAL3.SP.2: Metal3 to bent Metal3 spacing must be >= 0.18 um
3907 0 METAL3.W.3: Bent Metal3 (45 degree angle) width must be >= 0.16
3908 0 METAL4.SP.2: Metal4 to bent Metal4 spacing must be >= 0.18 um
3909 0 METAL4.W.3: Bent Metal4 (45 degree angle) width must be >= 0.16
3910 0 METAL5.SP.2: Metal5 to bent Metal5 spacing must be >= 0.18 um
3911 0 METAL5.W.3: Bent Metal5 (45 degree angle) width must be >= 0.16
3912 0 METAL6.SP.2: Metal6 to bent Metal6 spacing must be >= 0.18 um
3913 0 METAL6.W.3: Bent Metal6 (45 degree angle) width must be >= 0.16
3914 0 METAL7.SP.2: Metal7 to bent Metal7 spacing must be >= 0.18 um
3915 0 METAL7.W.3: Bent Metal7 (45 degree angle) width must be >= 0.16
3916 0 METAL1.A.1: Metal1 area must be >= 0.07 um
3917 0 METAL2.A.1: Metal2 area must be >= 0.08 um
3918 0 METAL3.A.1: Metal3 area must be >= 0.08 um
3919 0 METAL4.A.1: Metal4 area must be >= 0.08 um
3920 0 METAL5.A.1: Metal5 area must be >= 0.08 um
3921 0 METAL6.A.1: Metal6 area must be >= 0.08 um
3922 0 METAL7.A.1: Metal7 area must be >= 0.08 um
3923 0 METAL8.A.1: Metal8 area must be >= 0.2 um
3924 0 METAL9.A.1: Metal9 area must be >= 0.2 um
3926 0 VIA1.W.1: Via1 shapes must be 0.14x0.14 rectangles
3928 0 VIA1.SP.1: Via1 to Via1 spacing must be >= 0.15 um
3940 0 VIA1.SP.2: Via1 to Via1 spacing must be >= 0.20 um
3942 0 VIA2.W.1: Via2 shapes must be 0.14x0.14 rectangles
3944 0 VIA2.SP.1: Via2 to Via2 spacing must be >= 0.15 um
3956 0 VIA2.SP.2: Via2 to Via2 spacing must be >= 0.20 um
3958 0 VIA3.W.1: Via3 shapes must be 0.14x0.14 rectangles
3960 0 VIA3.SP.1: Via3 to Via3 spacing must be >= 0.15 um
3972 0 VIA3.SP.2: Via3 to Via3 spacing must be >= 0.20 um
3974 0 VIA4.W.1: Via4 shapes must be 0.14x0.14 rectangles
3976 0 VIA4.SP.1: Via4 to Via4 spacing must be >= 0.15 um
3988 0 VIA4.SP.2: Via4 to Via4 spacing must be >= 0.20 um
3990 0 VIA5.W.1: Via5 shapes must be 0.14x0.14 rectangles
3992 0 VIA5.SP.1: Via5 to Via5 spacing must be >= 0.15 um
4004 0 VIA5.SP.2: Via5 to Via5 spacing must be >= 0.20 um
4006 0 VIA6.W.1: Via6 shapes must be 0.14x0.14 rectangles
4008 0 VIA6.SP.1: Via6 to Via6 spacing must be >= 0.15 um
4020 0 VIA6.SP.2: Via6 to Via6 spacing must be >= 0.20 um
4022 0 VIA7.W.1: Via7 shapes must be 0.36x0.36 rectangles
4024 0 VIA7.SP.1: Via7 to Via7 spacing must be >= 0.36 um
4026 0 VIA8.W.1: Via8 shapes must be 0.36x0.36 rectangles
4028 0 VIA8.SP.1: Via8 to Via8 spacing must be >= 0.36 um
4029 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
4031 0 VIA1.E.1: Metal1 to Via1 enclosure must be >= 0.005 um
4035 0 VIA1.E.2: Metal1 to Via1 enclosure on opposite sides must be >= 0.06 um
4036 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
4038 0 VIA2.E.1: Metal2 to Via2 enclosure must be >= 0.005 um
4042 0 VIA2.E.2: Metal2 to Via2 enclosure on opposite sides must be >= 0.06 um
4043 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
4045 0 VIA3.E.1: Metal3 to Via3 enclosure must be >= 0.005 um
4049 0 VIA3.E.2: Metal3 to Via3 enclosure on opposite sides must be >= 0.06 um
4050 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
4052 0 VIA4.E.1: Metal4 to Via4 enclosure must be >= 0.005 um
4056 0 VIA4.E.2: Metal4 to Via4 enclosure on opposite sides must be >= 0.06 um
4057 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
4059 0 VIA5.E.1: Metal5 to Via5 enclosure must be >= 0.005 um
4063 0 VIA5.E.2: Metal5 to Via5 enclosure on opposite sides must be >= 0.06 um
4064 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
4066 0 VIA6.E.1: Metal6 to Via6 enclosure must be >= 0.005 um
4070 0 VIA6.E.2: Metal6 to Via6 enclosure on opposite sides must be >= 0.06 um
4071 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.03 um
4073 0 VIA7.E.1: Metal7 to Via7 enclosure must be >= 0.03 um
4077 0 VIA7.E.2: Metal7 to Via7 enclosure on opposite sides must be >= 0.08 um
4078 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.03 um
4080 0 VIA8.E.1: Metal8 to Via8 enclosure must be >= 0.03 um
4084 0 VIA8.E.2: Metal8 to Via8 enclosure on opposite sides must be >= 0.08 um
4351 0 LATCHUP.1: P+SD to NW tap spacing must be <= 25.0 um
4732 0 LATCHUP.2: N+SD to Psub tap spacing must be <= 25.0 um
4735 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 18.0 um
4736 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 18.0 um
4741 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 50.0 um when not blocked by a double guard ring
4745 0 LATCHUP.3: NMOS (I/O or ESD) to PMOS (I/O or ESD) spacing must be >= 50.0 um when not blocked by a double guard ring
4747 0 MSLOT1.W.1_MSLOT1.L.1: Metal1 Slot width/length must be >= 2.0 um
4749 0 MSLOT1.SP.1: Metal1 Slot to Metal1 Slot spacing must be >= 0.12 um
4751 0 MSLOT2.W.1_MSLOT2.L.1: Metal2 Slot width/length must be >= 2.0 um
4753 0 MSLOT2.SP.1: Metal2 Slot to Metal2 Slot spacing must be >= 0.14 um
4755 0 MSLOT3.W.1_MSLOT3.L.1: Metal3 Slot width/length must be >= 2.0 um
4757 0 MSLOT3.SP.1: Metal3 Slot to Metal3 Slot spacing must be >= 0.14 um
4759 0 MSLOT4.W.1_MSLOT4.L.1: Metal4 Slot width/length must be >= 2.0 um
4761 0 MSLOT4.SP.1: Metal4 Slot to Metal4 Slot spacing must be >= 0.14 um
4763 0 MSLOT5.W.1_MSLOT5.L.1: Metal5 Slot width/length must be >= 2.0 um
4765 0 MSLOT5.SP.1: Metal5 Slot to Metal5 Slot spacing must be >= 0.14 um
4767 0 MSLOT6.W.1_MSLOT6.L.1: Metal6 Slot width/length must be >= 2.0 um
4769 0 MSLOT6.SP.1: Metal6 Slot to Metal6 Slot spacing must be >= 0.14 um
4771 0 MSLOT7.W.1_MSLOT7.L.1: Metal7 Slot width/length must be >= 2.0 um
4773 0 MSLOT7.SP.1: Metal7 Slot to Metal7 Slot spacing must be >= 0.14 um
4775 0 MSLOT8.W.1_MSLOT8.L.1: Metal8 Slot width/length must be >= 2.0 um
4777 0 MSLOT8.SP.1: Metal8 Slot to Metal8 Slot spacing must be >= 0.44 um
4779 0 MSLOT9.W.1_MSLOT9.L.1: Metal9 Slot width/length must be >= 2.0 um
4781 0 MSLOT9.SP.1: Metal9 Slot to Metal9 Slot spacing must be >= 0.44 um
4785 0 ESD.1: ESD gate width must be >= 15.0 um and <= 65.0 um
4786 0 ESD.4: N+ source should connect to Pad or Bulk
4787 0 ESD.4: P+ source should connect to Pad or Nwell
4788 0 ESD.5: NMOS I/O and ESD devices must be inside P+ rings
4789 0 ESD.6: PMOS I/O and ESD devices must be inside N+ rings
4790 0 ESD.7: P+ taps can NOT butt NMOS I/O and ESD devices
4791 0 ESD.7: N+ taps can NOT butt PMOS I/O and ESD devices
4792 0 ESD.8: N+ drains must be non-salicided (except Contact area)
4793 0 ESD.8: P+ drains must be non-salicided (except Contact area)
4796 0 ESD.11: SiProt to Poly gate overlap must be >= 0.05 um
4798 0 ESD.12: SiProt to Poly gate enclosure must be >= 1.8 um
4800 0 ESD.13: SiProt to Oxide overlap must be >= 1.8 um
4804 0 ESD.14: ESD gate length must be == 0.3 um
4808 0 ESD.15: Poly gate to Cont spacing must be >= 0.25 um
4809 0 ESD.15: Poly gate to Cont spacing must be >= 0.25 um
4811 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
4813 0 BONDPAD.E.1: Metal1 to Bondpad enclosure must be >= 2.0 um
4814 0 BONDPAD.SP.2: Bondpad Metal1 to Metal1 spacing must be >= 3.0 um
4816 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
4818 0 BONDPAD.E.1: Metal2 to Bondpad enclosure must be >= 2.0 um
4819 0 BONDPAD.SP.2: Bondpad Metal2 to Metal2 spacing must be >= 3.0 um
4821 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
4823 0 BONDPAD.E.1: Metal3 to Bondpad enclosure must be >= 2.0 um
4824 0 BONDPAD.SP.2: Bondpad Metal3 to Metal3 spacing must be >= 3.0 um
4826 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
4828 0 BONDPAD.E.1: Metal4 to Bondpad enclosure must be >= 2.0 um
4829 0 BONDPAD.SP.2: Bondpad Metal4 to Metal4 spacing must be >= 3.0 um
4831 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
4833 0 BONDPAD.E.1: Metal5 to Bondpad enclosure must be >= 2.0 um
4834 0 BONDPAD.SP.2: Bondpad Metal5 to Metal5 spacing must be >= 3.0 um
4836 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
4838 0 BONDPAD.E.1: Metal6 to Bondpad enclosure must be >= 2.0 um
4839 0 BONDPAD.SP.2: Bondpad Metal6 to Metal6 spacing must be >= 3.0 um
4841 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
4843 0 BONDPAD.E.1: Metal7 to Bondpad enclosure must be >= 2.0 um
4844 0 BONDPAD.SP.2: Bondpad Metal7 to Metal7 spacing must be >= 3.0 um
4846 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
4848 0 BONDPAD.E.1: Metal8 to Bondpad enclosure must be >= 2.0 um
4849 0 BONDPAD.SP.2: Bondpad Metal8 to Metal8 spacing must be >= 3.0 um
4851 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
4853 0 BONDPAD.E.1: Metal9 to Bondpad enclosure must be >= 2.0 um
4854 0 BONDPAD.SP.2: Bondpad Metal9 to Metal9 spacing must be >= 3.0 um
4857 0 BONDPAD.W.1: Bondpad width must be >= 52.0 um
4859 0 BONDPAD.W.1: Bondpad width must be >= 52.0 um
4861 0 BONDPAD.SP.1: Bondpad to Bondpad spacing must be >= 8.0 um
4863 0 BONDPAD.B.1: Bondpad Metal1 beveled segments must be >= 1.8 um and <= 3.2 um
4865 0 BONDPAD.B.1: Bondpad Metal2 beveled segments must be >= 1.8 um and <= 3.2 um
4867 0 BONDPAD.B.1: Bondpad Metal3 beveled segments must be >= 1.8 um and <= 3.2 um
4869 0 BONDPAD.B.1: Bondpad Metal4 beveled segments must be >= 1.8 um and <= 3.2 um
4871 0 BONDPAD.B.1: Bondpad Metal5 beveled segments must be >= 1.8 um and <= 3.2 um
4873 0 BONDPAD.B.1: Bondpad Metal6 beveled segments must be >= 1.8 um and <= 3.2 um
4875 0 BONDPAD.B.1: Bondpad Metal7 beveled segments must be >= 1.8 um and <= 3.2 um
4877 0 BONDPAD.B.1: Bondpad Metal8 beveled segments must be >= 1.8 um and <= 3.2 um
4879 0 BONDPAD.B.1: Bondpad Metal9 beveled segments must be >= 1.8 um and <= 3.2 um
4882 0 BONDPAD.SP.3: Bondpad Via1 to Bondpad Via1 spacing must be >= 0.22 um
4885 0 BONDPAD.SP.3: Bondpad Via2 to Bondpad Via2 spacing must be >= 0.22 um
4888 0 BONDPAD.SP.3: Bondpad Via3 to Bondpad Via3 spacing must be >= 0.22 um
4891 0 BONDPAD.SP.3: Bondpad Via4 to Bondpad Via4 spacing must be >= 0.22 um
4894 0 BONDPAD.SP.3: Bondpad Via5 to Bondpad Via5 spacing must be >= 0.22 um
4897 0 BONDPAD.SP.3: Bondpad Via6 to Bondpad Via6 spacing must be >= 0.22 um
4900 0 BONDPAD.SP.4: Bondpad Via7 to Bondpad Via7 spacing must be >= 0.54 um
4903 0 BONDPAD.SP.4: Bondpad Via8 to Bondpad Via8 spacing must be >= 0.54 um
4905 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
4907 0 BONDPAD.E.2: Bondpad Metal1 to Via1 enclosure must be >= 0.05 um
4909 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
4911 0 BONDPAD.E.2: Bondpad Metal2 to Via2 enclosure must be >= 0.05 um
4913 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
4915 0 BONDPAD.E.2: Bondpad Metal3 to Via3 enclosure must be >= 0.05 um
4917 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
4919 0 BONDPAD.E.2: Bondpad Metal4 to Via4 enclosure must be >= 0.05 um
4921 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
4923 0 BONDPAD.E.2: Bondpad Metal5 to Via5 enclosure must be >= 0.05 um
4925 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
4927 0 BONDPAD.E.2: Bondpad Metal6 to Via6 enclosure must be >= 0.05 um
4929 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.09 um
4931 0 BONDPAD.E.3: Bondpad Metal7 to Via7 enclosure must be >= 0.09 um
4933 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.09 um
4935 0 BONDPAD.E.3: Bondpad Metal8 to Via8 enclosure must be >= 0.09 um
4937 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
4939 0 BONDPAD.E.2: Bondpad Metal2 to Via1 enclosure must be >= 0.05 um
4941 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
4943 0 BONDPAD.E.2: Bondpad Metal3 to Via2 enclosure must be >= 0.05 um
4945 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
4947 0 BONDPAD.E.2: Bondpad Metal4 to Via3 enclosure must be >= 0.05 um
4949 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
4951 0 BONDPAD.E.2: Bondpad Metal5 to Via4 enclosure must be >= 0.05 um
4953 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
4955 0 BONDPAD.E.2: Bondpad Metal6 to Via5 enclosure must be >= 0.05 um
4957 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
4959 0 BONDPAD.E.2: Bondpad Metal7 to Via6 enclosure must be >= 0.05 um
4961 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.09 um
4963 0 BONDPAD.E.3: Bondpad Metal8 to Via7 enclosure must be >= 0.09 um
4965 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.09 um
4967 0 BONDPAD.E.3: Bondpad Metal9 to Via8 enclosure must be >= 0.09 um
4968 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
4969 0 BONDPAD.SP.6: Bondpad Metal1 to Bondpad Metal1 spacing across first slot must be >= 1.00 um and <= 3.50 um
4970 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
4971 0 BONDPAD.SP.6: Bondpad Metal2 to Bondpad Metal2 spacing across first slot must be >= 1.00 um and <= 3.50 um
4972 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
4973 0 BONDPAD.SP.6: Bondpad Metal3 to Bondpad Metal3 spacing across first slot must be >= 1.00 um and <= 3.50 um
4974 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
4975 0 BONDPAD.SP.6: Bondpad Metal4 to Bondpad Metal4 spacing across first slot must be >= 1.00 um and <= 3.50 um
4976 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
4977 0 BONDPAD.SP.6: Bondpad Metal5 to Bondpad Metal5 spacing across first slot must be >= 1.00 um and <= 3.50 um
4978 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
4979 0 BONDPAD.SP.6: Bondpad Metal6 to Bondpad Metal6 spacing across first slot must be >= 1.00 um and <= 3.50 um
4980 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
4981 0 BONDPAD.SP.6: Bondpad Metal7 to Bondpad Metal7 spacing across first slot must be >= 1.00 um and <= 3.50 um
4982 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
4983 0 BONDPAD.SP.6: Bondpad Metal8 to Bondpad Metal8 spacing across first slot must be >= 1.00 um and <= 3.50 um
4985 0 BONDPAD.SP.7: Bondpad Via1 array to Bondpad Via1 array spacing must be >= 1.1 um
4987 0 BONDPAD.SP.7: Bondpad Via2 array to Bondpad Via2 array spacing must be >= 1.1 um
4989 0 BONDPAD.SP.7: Bondpad Via3 array to Bondpad Via3 array spacing must be >= 1.1 um
4991 0 BONDPAD.SP.7: Bondpad Via4 array to Bondpad Via4 array spacing must be >= 1.1 um
4993 0 BONDPAD.SP.7: Bondpad Via5 array to Bondpad Via5 array spacing must be >= 1.1 um
4995 0 BONDPAD.SP.7: Bondpad Via6 array to Bondpad Via6 array spacing must be >= 1.1 um
4997 0 BONDPAD.SP.7: Bondpad Via7 array to Bondpad Via7 array spacing must be >= 1.1 um
4999 0 BONDPAD.SP.7: Bondpad Via8 array to Bondpad Via8 array spacing must be >= 1.1 um
5002 0 OXIDER.W.1.1: Oxide resistor width must be >= 0.2 um
5005 0 POLYR.W.1.1: Poly resistor width must be >= 0.2 um
